### ISSUE TITLE
VisualGLM-6B的训练

### ISSUE THREAD

**Issue by WangRongsheng** [THUDM/VisualGLM-6B#1]
请问，会公布[VisualGLM-6B](https://github.com/THUDM/VisualGLM-6B) 的训练代码吗？

**Comment by ChrisTiger93** [comment]
+1,是否公开fintue代码

**Comment by Sleepychord** [comment]
会的，我们将在短期内提供一个finetune的样例，仓库内提供的sat模型架构就是训练的时候用的。

**Comment by WangRongsheng** [comment]
@Sleepychord Good jobs!
