### ISSUE TITLE
sat权重格式转换为hf格式

### ISSUE THREAD

**Issue by pokerc** [THUDM/VisualGLM-6B#147]
你好，请问可以提供下将sat权重格式转换为HF权重格式的脚本吗？
通过sat微调了模型，想通过HF做部署，但是没有在当前项目中找到权重格式转换的脚本。

**Comment by yysirs** [comment]
> 你好，请问可以提供下将sat权重格式转换为HF权重格式的脚本吗？ 通过sat微调了模型，想通过HF做部署，但是没有在当前项目中找到权重格式转换的脚本。

你好，请问通过sat微调是微调了ViT这部分嘛，你是怎么做的

**Comment by threeColorFr** [comment]
> 你好，请问可以提供下将sat权重格式转换为HF权重格式的脚本吗？ 通过sat微调了模型，想通过HF做部署，但是没有在当前项目中找到权重格式转换的脚本。

+1,请问解决了吗
