### ISSUE TITLE
您好，麻烦问下，模型推理结果有误

### ISSUE THREAD

**Issue by whyang78** [THUDM/VisualGLM-6B#179]
您好，我使用“模型推理”部分代码运行示例图片（examples/1.jpeg, 泰坦尼克号），但是程序运行结果偏差很大。
程序如下：
<img width="569" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/54824721/b67cdfa4-fd2b-452d-8b2b-408b63a9dc8e">
运行结果如下：
<img width="574" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/54824721/6875c40e-f067-4203-8a95-61ad4435e761">
感觉推理结果很离谱，我是按照文档说明进行配置的，一直搞不清楚哪里出了问题？我之前还试跑了您的chatglm和chatglm2，模型推理都没问题，所以感觉很奇怪，难道是visualglm的模型有问题？

**Comment by whyang78** [comment]
而且我输入的中文，为啥出来的结果是英文哈

**Comment by 910allen** [comment]
你好，我也遇到了相同的问题，请问您怎么解决的呀？

**Comment by 1049451037** [comment]
删除本地的checkpoint缓存（`~/.sat_models/visualglm-6b`），重新下载最新的checkpoint
