### ISSUE TITLE
请问visualglm最近有更新checkpoint吗？

### ISSUE THREAD

**Issue by whyang78** [THUDM/VisualGLM-6B#180]
我们最近更新了代码和checkpoint的格式，需要安装最新版的sat，visualglm的代码也要保证最新。

用新版本代码跑旧版本的checkpoint会报错，用旧版本代码跑新版本的checkpoint会出现推理错误。

_Originally posted by @1049451037 in https://github.com/THUDM/VisualGLM-6B/issues/178#issuecomment-1635382458_

**Comment by whyang78** [comment]
@lykeven @1049451037 您好，请问最近visualglm有更新模型权重吗？我在issue #179 遇到了模型推理有问题，请问是这样吗？十分感谢 （另外确定一下，main branch的代码是最新代码吧）

**Comment by 1049451037** [comment]
您好，更新了权重格式，但是没有更新权重数值。main分支是最新代码。你的issue #179应该不是这个问题。

**Comment by whyang78** [comment]
好像是我pytorch版本装的太高了，我装了个2.0，效果就有问题，现在换成1.12就没事了。十分感谢

**Comment by 1049451037** [comment]
@whyang78 建议换成sat版本的权重和代码，huggingface我们没有长期支持，sat版的torch2.0是没问题的。

**Comment by whyang78** [comment]
sat那个我之前也跑了，推理结果也有问题

**Comment by 1049451037** [comment]
具体是什么问题呢？是否sat没有更新到最新版本。

**Comment by whyang78** [comment]
@1049451037 我跑的模型推理代码，使用示例图片，最终推理结果有问题。sat版本是0.4.1

**Comment by whyang78** [comment]
我刚从我的新环境中跑了一次，能行了，看来之前版本太高有些地方出bug了吧

**Comment by 1049451037** [comment]
sat的torch2应该是没问题的，你可以试一下在你的torch2环境里用最新版的sat（>=0.4.1）代码跑一下。

**Comment by whyang78** [comment]
嗯嗯 好的



---- 回复的原邮件 ----
| 发件人 | Qingsong ***@***.***> |
| 日期 | 2023年07月17日 15:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [THUDM/VisualGLM-6B] 请问visualglm最近有更新checkpoint吗？ (Issue #180) |

sat的torch2应该是没问题的，你可以试一下在你的torch2环境里用最新版的sat（>=0.4.1）代码跑一下。
