### ISSUE TITLE
Lora微调后，将LoRA部分的参数合并到原始的权重时报错

### ISSUE THREAD

**Issue by ZJU-Andy-Lau** [THUDM/VisualGLM-6B#187]
采用README中merge_lora()代码进行合并时报错
![微信图片_20230719225257](https://github.com/THUDM/VisualGLM-6B/assets/72237792/63d05502-75b3-4d18-9f96-65ba8d8b55f6)

**Comment by 1049451037** [comment]
已修复，尝试安装github的sat：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

**Comment by ZJU-Andy-Lau** [comment]
已解决，谢谢！
同时想问一下p-tuning的结果应该如何进行合并呢？

**Comment by ZJU-Andy-Lau** [comment]
已解决，谢谢！
