### ISSUE TITLE
SwissArmyTransformer 使用最新版本 0.4.3 无法进行微调

### ISSUE THREAD

**Issue by vergil-ong** [THUDM/VisualGLM-6B#194]
![image](https://github.com/THUDM/VisualGLM-6B/assets/25544312/83c61083-50c2-4626-bca5-11f17c7853e4)
python 版本是3.9 或者  3.10 都试过 报错是一致的，不太懂是什么意思。我搜了下代码  源码是有thread_lock属性的，不太清楚为啥会报错，辛苦指教

**Comment by 1049451037** [comment]
`pip install filelock --upgrade`

**Comment by vergil-ong** [comment]
可以了 辛苦
