### ISSUE TITLE
推理时 图片 和描述不符

### ISSUE THREAD

**Issue by vergil-ong** [THUDM/VisualGLM-6B#196]
[![Uploading ce083a91eefd7cd520b424e989c9808.png…]()](https://github.com/vergil-ong/show-files/blob/main/github.png?raw=true)

python  3.9
pytorch 2.0.1
cuda 117
SwissArmyTransformer 0.4.3
windows 平台

**Comment by 1049451037** [comment]
你的checkpoint是从r2://visualglm-6b.zip下载的吗，还是清华云盘下载的

**Comment by vergil-ong** [comment]
截图 是 清华云盘

**Comment by 1049451037** [comment]
我们并没有提供过huggingface的清华云盘链接呀？你从哪里下载的

**Comment by vergil-ong** [comment]
readme 里面 https://cloud.tsinghua.edu.cn/d/43ffb021ca5f4897b56a/ 这个链接

**Comment by 1049451037** [comment]
哦，我找到了，在readme里确实有清华云盘的huggingface，我下载试一下。

**Comment by 1049451037** [comment]
但是从你的代码来看你并没有使用你下载的这个，而是重新下载的呀，是不是下载失败了

**Comment by vergil-ong** [comment]
我把 THUDM 放到项目目录里面了，咱们需要 用个国内的沟通方式吗？ 我这儿上传图片费劲。

**Comment by 1049451037** [comment]
先别急，我先本地下载试一下，看能否复现你的问题

**Comment by 1049451037** [comment]
我这边是没问题的，无法复现你的问题，请检查你的环境，尝试更新sat到最新版

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

**Comment by vergil-ong** [comment]
我这边是 windows pip install --no-deps  .
结果还是不太对
![image](https://github.com/THUDM/VisualGLM-6B/assets/25544312/546b4b7f-b744-48bb-95d2-1662140cc37a)

**Comment by 1049451037** [comment]
你输入的图片是什么，可以上传一下吗（不然我也不知道模型描述的对不对）

**Comment by vergil-ong** [comment]
example 里面的 1.jpeg

**Comment by 1049451037** [comment]
而且你下载的不对吧，github上的代码已经是0.4.3了，为什么你安装了一个0.4.1

**Comment by vergil-ong** [comment]
哦 那我重新 pull 一下 SwissArmyTransformer

**Comment by vergil-ong** [comment]
升级 SwissArmyTransformer 0.4.3  filelock  到 3.9.0 可以了

**Comment by vergil-ong** [comment]
升级 SwissArmyTransformer 0.4.3  filelock  到 3.9.0 可以了
辛苦大佬了
