### ISSUE TITLE
sat模型下载问题

### ISSUE THREAD

**Issue by pickmonster100** [THUDM/VisualGLM-6B#198]
![image](https://github.com/THUDM/VisualGLM-6B/assets/133647165/ce28f608-e44e-4b6d-ae3e-a7ebc8ddcfe8)
启动项目时下载sat模型，去了清华源下载，但是看其他issues说这个地址是旧的，我自己下载后启动包pad_token_id问题，与#188问题相同，请问怎么解决

**Comment by 1049451037** [comment]
重新pull一下VisualGLM-6B代码

**Comment by pickmonster100** [comment]
> 重新pull一下VisualGLM-6B代码

感谢你的回复，我已经通过手动修改源代码强制从正确的源下载，但我觉得这个是源代码的一个问题，希望官方可以修复
