### ISSUE TITLE
运行python cli_demo.py时报错ValueError: model_config.json must have key "model_class" for AutoModel.from_pretrained.

### ISSUE THREAD

**Issue by blockitigo** [THUDM/VisualGLM-6B#217]
执行python cli_demo.py时发生报错
![图片](https://github.com/THUDM/VisualGLM-6B/assets/71216040/6e818bda-d40d-4c1b-863e-33c100a0e9ad)
我希望下载运行sat的模型，请问是哪里出问题了。我没有设置SAT_HOME。

**Comment by 1049451037** [comment]
下错模型了吧，要用sat的模型而不是huggingface的模型

**Comment by blockitigo** [comment]
我重新拉了一套代码，安装依赖后，新建环境之后运行cli_demo.py 之后就可以下载sat模型了，所以怀疑可能是我之前的文件发生过改动？

**Comment by 1049451037** [comment]
代码会优先检查当前目录是否存在`visualglm-6b/`文件夹，可能你本地有一个huggingface的模型

**Comment by blockitigo** [comment]
> 代码会优先检查当前目录是否存在`visualglm-6b/`文件夹，可能你本地有一个huggingface的模型

也就是说如果一个文件夹下只能使用一种模型是吗。如果我希望运行cli_demo和cli_demo_hf只能分别创建单独的文件夹，然后各自运行。

**Comment by 1049451037** [comment]
你把文件夹重命名一下就好了，from_pretrained('visualglm-6b-hf')

**Comment by blockitigo** [comment]
> 

感谢！！
