### ISSUE TITLE
HF的输出结果和图片有很大误差，完全不相关

### ISSUE THREAD

**Issue by 13958806684** [THUDM/VisualGLM-6B#220]
我使用的是README中的测试代码，模型和参数是采用**本地上传**的模式。模型的下载使用的链接是“GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/THUDM/visualglm-6b”，参数的下载链接是“https://cloud.tsinghua.edu.cn/d/43ffb021ca5f4897b56a”，都是参考README给出的链接，模型和参数应该都是最新的才对。
```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("/home/experiment/VisualGLM-6B-main/visualglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("/home/experiment/VisualGLM-6B-main/visualglm-6b", trust_remote_code=True).half().cuda()
image_path = "/home/experiment/VisualGLM-6B-main/figure/test2.png"
response, history = model.chat(tokenizer, image_path, "这张图片中有什么", history=[])
print(response)
response, history = model.chat(tokenizer, image_path, "这张图片可能是在什么场所拍摄的？", history=history)
print(response)
```

然后图片也是示例图片：
![test2](https://github.com/THUDM/VisualGLM-6B/assets/77786733/ddbe1210-9c85-4026-9488-8c64a51339aa)
但是输出的结果是这样的：

> [2023-08-03 17:11:05,015] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2023-08-03 17:11:05,337] [INFO] [RANK 0] > initializing model parallel with size 1
> [2023-08-03 17:11:05,338] [INFO] [RANK 0] You are using model-only mode.
> For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
> /home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
>   warnings.warn("Initializing zero-element tensors is a no-op")
> Loading checkpoint shards: 100%|███████████████████████████████████████| 5/5 [00:07<00:00,  1.43s/it]
> Specify both input_ids and inputs_embeds at the same time, will use inputs_embeds
> 这张照片中有一个白色房屋，有一棵大树和一条小河。这棵树很高大，树干粗壮，树叶茂密。小河清澈见底，周围一片宁静。画面中没有其他人或动物的存在，只有一座房子和一个场景。这是一个自然美景的场景，可以让人们感受到大自然的美丽和平静。
> 这张图片是在一个自然环境下拍摄到的，可能位于森林、公园或者乡村地区。照片中的这棵大树和清澈的小河表明这个地点是一个适合居住和生活的地方，人们可以享受清新的空气和美丽的景色。

我翻阅了前面的issue，这个结果可能是因为模型和checkpoint不一致的原因，但我都是使用readme中的最新链接下载的。或者图片链接未给出，但是按照这个示例代码似乎不应该有这样的问题。

**Comment by 1049451037** [comment]
请更新sat代码到最新版：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

**Comment by 13958806684** [comment]
ok解决了，谢谢
