### ISSUE TITLE
SAT_HOME里已经有下载好了模型了，运行web_demo里还要再下载一次呢？

### ISSUE THREAD

**Issue by dydwgmcnl4241** [THUDM/VisualGLM-6B#23]

**Comment by dydwgmcnl4241** [comment]
<img width="1026" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/122611406/ad87bf0b-f58f-4a0e-a3b6-206652ce5d12">

**Comment by Sleepychord** [comment]
看上去是SAT_HOME设置的时候使用了相对路径，可以改成绝对路径应该就行了

**Comment by dydwgmcnl4241** [comment]
的确是，谢谢~~
