### ISSUE TITLE
model use left-padding or right-padding ??

### ISSUE THREAD

**Issue by iamsile** [THUDM/VisualGLM-6B#27]
您好，请问VisualGLM-6B在训练时用的是left-padding还是right-padding，我在用VisualGLM-6B训练reward model时，会报assert divergence_ind >0的错误，打印信息时发现divergence_ind[0]，我去deepspeed上查了一下，说是模型padding导致的，所以想咨询一下，VisualGLM-6B是left-padding还是right-padding

<img width="546" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/2016205/8c377d47-0b62-4d20-8c20-68abc2d3e9a9">

期待您的回复

**Comment by Sleepychord** [comment]
文本部分是right padding

**Comment by iamsile** [comment]
好的，感谢感谢
