### ISSUE TITLE
单机多卡微调 进程被killed

### ISSUE THREAD

**Issue by abbhay** [THUDM/VisualGLM-6B#290]
![f85c2c77db46c566f79a173f134080c](https://github.com/THUDM/VisualGLM-6B/assets/36267615/3e05d4d1-6ddd-401c-bd07-1e16d9de4561)
![9b226ef0a488c3214cbe003814d691e](https://github.com/THUDM/VisualGLM-6B/assets/36267615/a3f55fc3-83c6-4fc4-bc42-08f6d51da4a5)
使用2个V100进行单机多卡微调的时候出现了进程被杀 旨在sh代码里面加了 --include localhost:0,1 请问大佬这种是什么原因列

**Comment by 1049451037** [comment]
应该是你的cpu内存不够导致进程被kill了，尝试安装github最新版SAT：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

新版对cpu内存进行了优化，在你的程序里from_pretrained函数加入`from_pretrained(..., overwrite_args={'model_parallel_size': 1})`即可使用cpu内存优化模式。

**Comment by 1049451037** [comment]
应该是你的cpu内存不够导致进程被kill了，尝试安装github最新版SAT：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

新版对cpu内存进行了优化，在你的程序里from_pretrained函数加入`from_pretrained(..., overwrite_args={'model_parallel_size': 1})`即可使用cpu内存优化模式。

**Comment by abbhay** [comment]
> 应该是你的cpu内存不够导致进程被kill了，尝试安装github最新版SAT：
> 
> ```
> git clone https://github.com/THUDM/SwissArmyTransformer
> cd SwissArmyTransformer
> pip install .
> ```
> 
> 新版对cpu内存进行了优化，在你的程序里from_pretrained函数加入`from_pretrained(..., overwrite_args={'model_parallel_size': 1})`即可使用cpu内存优化模式。
![8c52b00b29302d70f29d79c0cdea616](https://github.com/THUDM/VisualGLM-6B/assets/36267615/c02c6576-019c-44e8-b351-5d4c8940afcb)
添加这段代码后，仍然报错，并且进程被kill
 RuntimeError: Tensors must be CUDA and dense

**Comment by abbhay** [comment]
![8c52b00b29302d70f29d79c0cdea616](https://github.com/THUDM/VisualGLM-6B/assets/36267615/bd522446-9fbe-46ac-af17-f3d318496317)

**Comment by 1049451037** [comment]
For reference: 进一步优化内存，把`args.device = 'cpu'`改成`args.device = 'cuda'`。
