### ISSUE TITLE
在A40（46G，4张）上微调失败

### ISSUE THREAD

**Issue by cdqncn** [THUDM/VisualGLM-6B#295]
使用命令bash finetune/finetune_visualglm.sh进行微调，最后程序直接exits with return code=-7退出了，没法进行错误溯源，求大佬解答
![bug](https://github.com/THUDM/VisualGLM-6B/assets/47705034/c590da00-da75-4396-9ea0-ca47fa0ae357)

**Comment by 1049451037** [comment]
应该是内存不够导致被kill了。可以把代码里args.device = 'cpu'改成args.device = 'cuda'试一下。

**Comment by cdqncn** [comment]
改成args.device = 'cuda'还是一样的错误，跑不起来

![a252999ba1a0641fef4faccd6add51b](https://github.com/THUDM/VisualGLM-6B/assets/47705034/49fe6837-a446-4a8b-9930-55846e810b04)

**Comment by 1049451037** [comment]
那就安装一下github最新的sat：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

https://github.com/THUDM/VisualGLM-6B/blob/f4429a009ee533b76e8757dce6917fbf0b0408f9/finetune_visualglm.py#L178

然后把这段代码变成：

```
model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args, overwrite_args={'model_parallel_size': 1})
```

**Comment by cdqncn** [comment]
还是不行，哎，太难了
![IMG_1763](https://github.com/THUDM/VisualGLM-6B/assets/47705034/2285804f-00f6-42c6-99ee-023430a2e32d)

**Comment by 1049451037** [comment]
这是配置错误导致的，运行已经成功了。

**Comment by 1049451037** [comment]
> 那就安装一下github最新的sat：
> 
> ```
> git clone https://github.com/THUDM/SwissArmyTransformer
> cd SwissArmyTransformer
> pip install .
> ```
> 
> https://github.com/THUDM/VisualGLM-6B/blob/f4429a009ee533b76e8757dce6917fbf0b0408f9/finetune_visualglm.py#L178
> 
> 然后把这段代码变成：
> 
> ```
> model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args, overwrite_args={'model_parallel_size': 1})
> ```

需要更新sat。

**Comment by cdqncn** [comment]
我直接下载的
<img width="255" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/47705034/ce0417fb-2d53-4f01-981b-0abc74a5122b">
然后安装的，和github版本有区别嘛

**Comment by 1049451037** [comment]
有区别啊，就是为了给你解决这个问题才更新的github代码

**Comment by cdqncn** [comment]
我公司堡垒机没网络，可以用自己的电脑执行你的这段代码，把SwissArmyTransformer-0.4.8-py3-none-any.whl文件下下来，然后带上去吗

**Comment by 1049451037** [comment]
可以把git仓库的代码拷贝下来带上去

**Comment by cdqncn** [comment]
你好，我按照您的更新了，也改了代码，也指定了cuda 而不是cpu ，现在又变成return code =-7退出了
![Uploading IMG_1799.jpeg…]()

**Comment by 1049451037** [comment]
看不到你上传的图片

**Comment by cdqncn** [comment]
![IMG_1799](https://github.com/THUDM/VisualGLM-6B/assets/47705034/87b34adf-3ae5-4188-873c-973826b9b384)
抱歉，刚删了，这个还是有问题，您是在容器里跑的吗？还是本机跑的

**Comment by cdqncn** [comment]
可以了兄弟，我是因为docker分配的内存不够，加上she size 60G就好了
