### ISSUE TITLE
web_demo_hf.py报错：RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by MingJiaAn** [THUDM/VisualGLM-6B#3]
在上传图片之后，运行报错，错误信息如下：
Traceback (most recent call last):
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/mnt/amj/VisualGLM-6B/web_demo_hf.py", line 63, in predict
    for response, history in model.stream_chat(tokenizer, image_path, input, history, max_length=max_length, top_p=top_p,
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/visualglm-6b/modeling_chatglm.py", line 1439, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/visualglm-6b/modeling_chatglm.py", line 1291, in stream_generate
    outputs = self(
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/visualglm-6b/modeling_chatglm.py", line 1462, in forward
    image_embeds = self.image_encoder(images)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/visualglm-6b/visual.py", line 69, in forward
    enc = self.vit(image)[0]
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/visualglm-6b/visual.py", line 28, in forward
    return super().forward(input_ids=input_ids, position_ids=None, attention_mask=attention_mask, image=image)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/sat/model/base_model.py", line 144, in forward
    return self.transformer(*args, **kwargs)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/sat/model/transformer.py", line 451, in forward
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/sat/model/official/vit_model.py", line 55, in word_embedding_forward
    embeddings = self.proj(images)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/amj/conda/envs/lora/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by Sleepychord** [comment]
似乎是没有半精度卷积算子导致的，可否提供您的运行环境和其他信息？

**Comment by MingJiaAn** [comment]
> 似乎是没有半精度卷积算子导致的，可否提供您的运行环境和其他信息？

装的包比较多，麻烦您了
absl-py                  1.3.0
accelerate               0.17.1
aiodns                   3.0.0
aiofile                  3.8.5
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   4.2.2
antlr4-python3-runtime   4.9.3
anyio                    3.6.2
appdirs                  1.4.4
argilla                  1.6.0
astor                    0.8.1
asttokens                2.0.5
async-timeout            4.0.2
attrdict                 2.0.1
attrs                    22.2.0
Babel                    2.12.1
backcall                 0.2.0
backoff                  2.2.1
bce-python-sdk           0.8.83
bcrypt                   4.0.1
beautifulsoup4           4.12.2
bitsandbytes             0.37.1
black                    21.4b2
blinker                  1.4
bottle                   0.12.25
Bottleneck               1.3.5
Brotli                   1.0.9
brotlipy                 0.7.0
cachetools               4.2.2
caio                     0.9.12
certifi                  2022.12.7
cffi                     1.15.1
chardet                  4.0.0
charset-normalizer       3.1.0
click                    8.1.3
cloudpickle              2.2.1
cmake                    3.26.1
coloredlogs              15.0.1
comm                     0.1.2
commonmark               0.9.1
contourpy                1.0.7
cpm-kernels              1.0.11
cryptography             39.0.1
cssselect                1.2.0
cssutils                 2.6.0
cycler                   0.11.0
Cython                   0.29.34
dataclasses-json         0.5.7
datasets                 2.10.1
debugpy                  1.5.1
decorator                5.1.1
deepspeed                0.8.3
Deprecated               1.2.13
dill                     0.3.6
docker-pycreds           0.4.0
effdet                   0.3.0
einops                   0.6.1
entrypoints              0.4
et-xmlfile               1.1.0
executing                0.8.3
faiss-cpu                1.7.4
fastapi                  0.95.0
ffmpy                    0.3.0
filelock                 3.10.7
fire                     0.5.0
Flask                    2.2.3
flask-babel              3.1.0
Flask-Cors               3.0.10
flatbuffers              23.3.3
flit_core                3.8.0
fonttools                4.39.3
frozenlist               1.3.3
fsspec                   2023.3.0
future                   0.18.3
fvcore                   0.1.5.post20221221
gevent                   22.10.2
geventhttpclient         2.0.2
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.6.0
google-auth-oauthlib     0.4.4
gradio                   3.28.3
gradio_client            0.2.4
greenlet                 2.0.2
grpcio                   1.42.0
h11                      0.12.0
hjson                    3.1.0
httpcore                 0.15.0
httpx                    0.23.3
huggingface-hub          0.13.3
humanfriendly            10.0
hydra-core               1.3.2
icetk                    0.0.4
idna                     3.4
imageio                  2.28.1
imgaug                   0.4.0
importlib-metadata       6.1.0
importlib-resources      5.12.0
iopath                   0.1.9
ipykernel                6.19.2
ipython                  8.10.0
ipywidgets               8.0.4
itsdangerous             2.1.2
jedi                     0.18.1
jieba                    0.42.1
Jinja2                   3.1.2
joblib                   1.2.0
jsonschema               4.17.3
jupyter_client           8.1.0
jupyter_core             5.3.0
jupyterlab-widgets       3.0.5
kiwisolver               1.4.4
langchain                0.0.146
latex2mathml             3.75.5
layoutparser             0.3.4
lazy_loader              0.2
linkify-it-py            2.0.0
lit                      16.0.0
lmdb                     1.4.1
lmflow                   0.0.1              /mnt/amj/LMFlow/src
lxml                     4.9.2
Markdown                 3.4.1
markdown-it-py           2.2.0
MarkupSafe               2.1.2
marshmallow              3.19.0
marshmallow-enum         1.5.1
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdit-py-plugins          0.3.3
mdtex2html               1.2.0
mdurl                    0.1.2
mkl-fft                  1.3.1
mkl-random               1.2.2
mkl-service              2.4.0
monotonic                1.6
mpi4py                   3.1.4
mpmath                   1.3.0
msg-parser               1.2.0
multidict                6.0.4
multiprocess             0.70.14
mypy-extensions          1.0.0
nest-asyncio             1.5.6
networkx                 3.0
ninja                    1.11.1
nltk                     3.8.1
numexpr                  2.8.4
numpy                    1.23.5
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
olefile                  0.46
omegaconf                2.3.0
onnx                     1.12.0
onnxruntime              1.14.1
openapi-schema-pydantic  1.2.4
opencv-contrib-python    4.6.0.66
opencv-python            4.6.0.66
openpyxl                 3.1.2
opt-einsum               3.3.0
orjson                   3.8.9
packaging                23.0
paddle-bfloat            0.1.7
paddle2onnx              1.0.6
paddleocr                2.6.1.3
paddlepaddle             2.4.2
pandas                   1.5.3
paramiko                 3.1.0
parso                    0.8.3
pathspec                 0.11.1
pathtools                0.1.2
pdf2docx                 0.5.6
pdf2image                1.16.3
pdfminer.six             20221105
pdfplumber               0.9.0
peft                     0.3.0.dev0
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.0.1
platformdirs             2.5.2
portalocker              2.7.0
premailer                3.10.0
prompt-toolkit           3.0.36
protobuf                 3.20.0
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
py-cpuinfo               9.0.0
pyarrow                  11.0.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycares                  4.3.0
pyclipper                1.3.0.post4
pycocotools              2.0.6
pycparser                2.21
pycryptodome             3.17
pydantic                 1.10.7
pydeck                   0.7.1
pydot                    1.4.2
pydub                    0.25.1
Pygments                 2.15.1
PyJWT                    2.6.0
Pympler                  0.9
PyMuPDF                  1.20.2
PyNaCl                   1.5.0
pyOpenSSL                23.0.0
pypandoc                 1.11
pyparsing                3.0.9
pypinyin                 0.48.0
pyrsistent               0.19.3
PySocks                  1.7.1
pytesseract              0.3.10
python-dateutil          2.8.2
python-docx              0.8.11
python-magic             0.4.27
python-multipart         0.0.6
python-pptx              0.6.21
python-rapidjson         1.10
pytz                     2023.3
PyWavelets               1.4.1
PyYAML                   6.0
pyzmq                    23.2.0
rapidfuzz                3.0.0
rarfile                  4.0
regex                    2023.3.23
requests                 2.28.2
requests-oauthlib        1.3.0
responses                0.18.0
rfc3986                  1.5.0
rich                     12.5.1
rouge-chinese            1.0.3
rsa                      4.7.2
scikit-image             0.20.0
scikit-learn             1.2.2
scipy                    1.9.1
semantic-version         2.10.0
semver                   2.13.0
sentence-transformers    2.2.2
sentencepiece            0.1.97
sentry-sdk               1.18.0
setproctitle             1.3.2
setuptools               65.6.3
shapely                  2.0.1
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
soupsieve                2.4.1
SQLAlchemy               1.4.48
stack-data               0.2.0
starlette                0.26.1
stream-chat              4.7.0
streamlit                1.20.0
streamlit-chat           0.0.2.2
SwissArmyTransformer     0.3.6
sympy                    1.11.1
tabulate                 0.9.0
tenacity                 8.2.2
tensorboard              2.11.0
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tensorboardX             2.6
termcolor                2.3.0
threadpoolctl            3.1.0
tifffile                 2023.4.12
timm                     0.6.13
tokenizers               0.13.2
toml                     0.10.2
toolz                    0.12.0
torch                    2.0.0
torchvision              0.15.1
tornado                  6.2
tqdm                     4.65.0
traitlets                5.7.1
transformers             4.27.1
triton                   2.0.0
tritonclient             2.33.0
trl                      0.4.2.dev0
typing_extensions        4.5.0
typing-inspect           0.8.0
tzlocal                  2.1
uc-micro-py              1.0.1
unstructured             0.6.3
unstructured-inference   0.4.4
urllib3                  1.26.15
uvicorn                  0.21.1
validators               0.18.2
visualdl                 2.5.1
Wand                     0.6.11
wandb                    0.14.0
watchdog                 2.1.6
wcwidth                  0.2.5
websockets               11.0
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       4.0.5
wrapt                    1.14.1
x2paddle                 1.4.1
XlsxWriter               3.1.0
xxhash                   3.2.0
yacs                     0.1.8
yarl                     1.8.2
zipp                     3.15.0
zope.event               4.6
zope.interface           6.0

**Comment by MingJiaAn** [comment]
> 似乎是没有半精度卷积算子导致的，可否提供您的运行环境和其他信息？

您能说下正确的环境吗？比如需要的包详细的版本

**Comment by Sleepychord** [comment]
https://github.com/microsoft/TaskMatrix/issues/283#issuecomment-1497346164 你看一下这个回答，好像是降低pytorch版本到1.13就行
