### ISSUE TITLE
finetune中断了，怎么resume？

### ISSUE THREAD

**Issue by chenjingcheng** [THUDM/VisualGLM-6B#300]
如题，谢谢！

**Comment by 1049451037** [comment]
https://github.com/THUDM/VisualGLM-6B/blob/f4429a009ee533b76e8757dce6917fbf0b0408f9/finetune_visualglm.py#L177

把visualglm-6b换成你新训练的路径。

**Comment by chenjingcheng** [comment]
哦，谢谢
