### ISSUE TITLE
finetune 128的图片跟224的图片，显存的占用和每个迭代都没有减少！

### ISSUE THREAD

**Issue by chenjingcheng** [THUDM/VisualGLM-6B#302]
finetune 128的图片跟224的图片，显存的占用和每个迭代都没有减少！
我是4090，单卡
我把finetune的图片尺寸修改成128后，发现同样的batchsize数据和其他的一样的参数：
1、显存占用没有改变，无法增加batchsize，只能跟224一样的，batchsize为6
2、迭代的时间也没有减少，每个迭代几乎是一样的。

根据以前的经验，显存使用应该减少，时间更是加快。
不知道是那里没有修改对？

**Comment by 1049451037** [comment]
因为输入的图像分辨率是固定的：

https://github.com/THUDM/VisualGLM-6B/blob/f4429a009ee533b76e8757dce6917fbf0b0408f9/finetune_visualglm.py#L158

如果你想修改，可以参考这个：https://github.com/THUDM/VisualGLM-6B/issues/296

**Comment by chenjingcheng** [comment]
ok，谢谢您的回复！
