### ISSUE TITLE
Error when loading local model: ValueError: Unrecognized configuration class <class 'transformers_modules.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.

### ISSUE THREAD

**Issue by Mingyu-Wei** [THUDM/VisualGLM-6B#307]
I downloaded the model locally, and when I run this line, the error occurs.
```
model = AutoModelForCausalLM.from_pretrained(model_path, truse_remote_code=True)
```
I've looked at solutions in https://github.com/THUDM/ChatGLM-6B/issues/153 and https://github.com/THUDM/ChatGLM-6B/issues/37, but it doesn't seem to help.

I understand that the problem might be solved if I directly load the model from huggingface, but I think it's still a problem here

**Comment by 1049451037** [comment]
I think you should upgrade your `transformers` package.

```
pip install git+https://github.com/huggingface/transformers
```

**Comment by 1049451037** [comment]
Then it's the problem of your downloaded model. Try download it from official repo.

**Comment by Mingyu-Wei** [comment]
> Use AutoModel instead of AutoModelForCausalLM if you are using VisualGLM-6B.

Thanks, that is indeed the problem
