### ISSUE TITLE
在运行web_demo时，报错AttributeError: 'Chatbot' object has no attribute 'style'.

### ISSUE THREAD

**Issue by hzh0720** [THUDM/VisualGLM-6B#315]
你好，我在运行```web_demo```时，报错```AttributeError: 'Chatbot' object has no attribute 'style'.Did you mean: 'scale'?```
报错出现在```web_demo.py```的第103行：
```result_text = gr.components.Chatbot(label='Multi-round conversation History', value=[("", "Hi, What do you want to know about this image?")]).style(height=550)```
我在尝试了以下几种方法但没有成功：
1.更新`gradio`后（目前版本4.1.2），没有解决这个问题
2.将`.style(height=550)`换成`.scale(height=550)`会报返回值为空；
3.将`.style(height=550)`直接去掉后，没有报错，但会有warning，最后会直接退出```web_demo```的运行
希望可以帮忙解决，谢谢！！

**Comment by 1049451037** [comment]
@lykeven Hi, Yan, could you help with this issue?

**Comment by hzh0720** [comment]
解决了！
问题出现在`gradio`在4.0版本以后去除了.style()函数
解决办法是将`gradio`回退到4.0以前，之后便可以正常运行

**Comment by stonetears** [comment]
we can use gradio 4.* like this :  Chatbot().height=500

**Comment by qqq286** [comment]
> 解决了！ 问题出现在`gradio`在4.0版本以后去除了.style()函数 解决办法是将`gradio`回退到4.0以前，之后便可以正常运行

![微信图片_20241012154819](https://github.com/user-attachments/assets/44c38385-ebb0-4809-adc4-dc1e02ef18bb)
gradio退回之后，页面显示这样，请问怎么办呀
