### ISSUE TITLE
一个badcase

### ISSUE THREAD

**Issue by lucasjinreal** [THUDM/VisualGLM-6B#4]
![image](https://github.com/THUDM/VisualGLM-6B/assets/21303438/ef81a487-eee3-4072-a01b-db25950f296a)

**Comment by Sleepychord** [comment]
抱歉对此场景效果不佳，由于数据等方面原因，模型暂时不具有中文ocr的能力（英文ocr能力有一些），我们会在下个版本中增加这个能力。
