### ISSUE TITLE
如果要基于 chatglm-6b 来训练一个多模态语言模型，glm 的 token部分该怎么处理呢？

### ISSUE THREAD

**Issue by shtdbb** [THUDM/VisualGLM-6B#50]
最近想模仿微软的 LLaMA 结构训练一个多模态语言模型，也就是要把图像的 token 向量和文本的 embedding 向量拼成一段话输入 chatglm。目前看网上的微调代码都是基于 token 的编码 input_ids 输入模型的，大致看了仓库的代码，这个项目貌似是把图像和文本通过向量输入的，如果是 chatglm，怎么使用嵌入向量输入模型呀，因为我看预测 token 也是预测的 token id，然后再把预测的 id 和输入拼起来再预测下一个。向量输入的话，是把预测 id 的嵌入向量得到再和输入向量拼起来吗？

**Comment by Sleepychord** [comment]
可以看我们之前的文章cogview2，http://github.com/THUDM/CogView2 ，是你说的用token的语言模型的思路，结合了双向理解和生成，你可以用此思路和预训练llama结合一下。本仓库直接使用图像的feature，不需要自回归生成图像。

**Comment by shtdbb** [comment]
> 可以看我们之前的文章cogview2，[http://github.com/THUDM/CogView2](https://github.com/THUDM/CogView2) ，是你说的用token的语言模型的思路，结合了双向理解和生成，你可以用此思路和预训练llama结合一下。本仓库直接使用图像的feature，不需要自回归生成图像。

想再请教一下代码细节，我看代码里图片有一个 `image_length` 默认为 32，这个是图片的 patch size 吗？然后图片经过 ViT 和 Q-Former 以后又进入了一个投影层转换维度是不是也可以看做是和 word_embedding 对齐的操作？然后视觉模型里面的 `Mixin` 这个名字是什么意思呀？
感谢~

**Comment by shtdbb** [comment]
> 可以看我们之前的文章cogview2，[http://github.com/THUDM/CogView2](https://github.com/THUDM/CogView2) ，是你说的用token的语言模型的思路，结合了双向理解和生成，你可以用此思路和预训练llama结合一下。本仓库直接使用图像的feature，不需要自回归生成图像。

想再请教一下代码细节，我看代码里图片有一个 `image_length` 默认为 32，这个是图片的 patch size 吗？然后图片经过 ViT 和 Q-Former 以后又进入了一个投影层转换维度是不是也可以看做是和 word_embedding 对齐的操作？然后视觉模型里面的 `Mixin` 这个名字是什么意思呀？
感谢~
