### ISSUE TITLE
Finetune to others language ?

### ISSUE THREAD

**Issue by batman-do** [THUDM/VisualGLM-6B#51]
How I can finetune in other language , maybe vietnamese, ? thanks guys, awesome project

**Comment by Sleepychord** [comment]
I can provide some steps:
1. check http://github.com/THUDM/icetk whether it can tokenize vietnamese. if so, it is possible to fine-tune it to vietnamese.
2. preparing some image-vietnamese pairs and other vqa data.
3. finetuning the model using sat.

**Comment by batman-do** [comment]
> I can provide some steps:
> 
> 1. check [http://github.com/THUDM/icetk](https://github.com/THUDM/icetk) whether it can tokenize vietnamese. if so, it is possible to fine-tune it to vietnamese.
> 2. preparing some image-vietnamese pairs and other vqa data.
> 3. finetuning the model using sat.

Thanks guy, I'try this !
