### ISSUE TITLE
windows 安装不了依赖

### ISSUE THREAD

**Issue by happyi** [THUDM/VisualGLM-6B#6]
ERROR: Command errored out with exit status 1:                                                                           command: 'c:\program files\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-iozsj5rb\\deepspeed_cd9c08b77eaf40568b910542cdc41a19\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-iozsj5rb\\deepspeed_cd9c08b77eaf40568b910542cdc41a19\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-sdfey28f'                                                                                                    cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-iozsj5rb\deepspeed_cd9c08b77eaf40568b910542cdc41a19\                                                                                                                            Complete output (14 lines):                                                                                             test.c                                                                                                                  LINK : fatal error LNK1181: cannot open input file 'aio.lib'                                                            Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "C:\Users\Administrator\AppData\Local\Temp\pip-install-iozsj5rb\deepspeed_cd9c08b77eaf40568b910542cdc41a19\setup.py", line 162, in <module>                                                                                                  abort(f"Unable to pre-compile {op_name}")                                                                             File "C:\Users\Administrator\AppData\Local\Temp\pip-install-iozsj5rb\deepspeed_cd9c08b77eaf40568b910542cdc41a19\setup.py", line 51, in abort                                                                                                      assert False, msg                                                                                                   AssertionError: Unable to pre-compile async_io                                                                          DS_BUILD_OPS=1

**Comment by Sleepychord** [comment]
请看安装部分的readme，这就是里面提到的问题：

此时默认会安装deepspeed库（支持sat库训练），此库对于模型推理并非必要，同时部分Windows环境安装此库时会遇到问题。如果想绕过deepspeed安装，我们可以将命令改为
```
pip install -r requirements_wo_ds.txt
pip install --no-deps 'SwissArmyTransformer>=0.3.6'
```
Windows上我们经过测试用此方法是可以正常运行的。

**Comment by happyi** [comment]
> 请看安装部分的readme，这就是里面提到的问题：
> 
> 此时默认会安装deepspeed库（支持sat库训练），此库对于模型推理并非必要，同时部分Windows环境安装此库时会遇到问题。如果想绕过deepspeed安装，我们可以将命令改为
> 
> ```
> pip install -r requirements_wo_ds.txt
> pip install --no-deps 'SwissArmyTransformer>=0.3.6'
> ```
> 
> Windows上我们经过测试用此方法是可以正常运行的。

pip install --no-deps 'SwissArmyTransformer>=0.3.6'   就是这个命令报的错

**Comment by magicwang1111** [comment]
E:\VisualGLM-6B>pip install --no-deps 'SwissArmyTransformer>=0.3.6'
ERROR: Invalid requirement: "'SwissArmyTransformer"
一样的报错
已经pip install -r requirements_wo_ds.txt了

**Comment by Sleepychord** [comment]
请将这里的单引号转为双引号，Windows似乎只支持双引号。我已经在readme更新了
