### ISSUE TITLE
加载FineTuneVisualGLMModel.from_pretrained时，如何将下载的模型放到指定地址？

### ISSUE THREAD

**Issue by Changanyue** [THUDM/VisualGLM-6B#60]
系统盘存不下。
加载本地的预训练的话，报错缺少model_config.json

sat/model/base_model.py
--
189 | # recorded in arguments.py: add_model_config_args
190 | return parser
 
211 | args = cls.get_args()
212 | args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
213 | args = overwrite_args_by_dict(args, overwrite_args=overwrite_args)

**Comment by PurpleMStone** [comment]
指定SAT_HOME，运行web_demo.py 还是下载到系统盘了？

> 应该是下载的checkpoint错误导致的，需要使用[sat的checkpoint](https://github.com/THUDM/VisualGLM-6B/blob/main/model/visualglm.py#L9)（默认会从清华云盘下载，通过设置`SAT_HOME`环境变量可以指定下载目录），你下载的应该是huggingface的版本，没有model_config.json文件
