### ISSUE TITLE
直接运行cli_demo.py报错No module named 'sat'，并不会自动下载sat模型

### ISSUE THREAD

**Issue by Senna1960321** [THUDM/VisualGLM-6B#62]
from sat.model.mixins import CachedAutoregressiveMixin
ModuleNotFoundError: No module named 'sat'

**Comment by PurpleMStone** [comment]
运行 python web_demo.py遇到同样的问题...
  File "/data/GLM/VisualGLM-6B/model/chat.py", line 19, in <module>
    from sat.generation.autoregressive_sampling import filling_sequence, BaseStrategy
ModuleNotFoundError: No module named 'sat'

**Comment by PurpleMStone** [comment]
> 运行 python web_demo.py遇到同样的问题... File "/data/GLM/VisualGLM-6B/model/chat.py", line 19, in from sat.generation.autoregressive_sampling import filling_sequence, BaseStrategy ModuleNotFoundError: No module named 'sat'

______
安装完requirements.txt的依赖包就可以了。报错这里的sat是说sat库，不是sat模型

**Comment by Senna1960321** [comment]
> > 运行 python web_demo.py遇到同样的问题... File "/data/GLM/VisualGLM-6B/model/chat.py", line 19, in from sat.generation.autoregressive_sampling import filling_sequence, BaseStrategy ModuleNotFoundError: No module named 'sat'
> 
> 安装完requirements.txt的依赖包就可以了。报错这里的sat是说sat库，不是sat模型

可requirements.txt我都安装好了，除了deepspeed库

**Comment by liudenghuiv** [comment]
ModuleNotFoundError: No module named 'sat'指的是没有安装  SwissArmyTransformer
``pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-deps "SwissArmyTransformer> =0.3.6"
安装即可！

**Comment by Senna1960321** [comment]
> ModuleNotFoundError: No module named 'sat'指的是没有安装 SwissArmyTransformer ``pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-deps "SwissArmyTransformer> =0.3.6" 安装即可！
好的多谢

**Comment by paomian001** [comment]
> > ModuleNotFoundError: No module named 'sat'指的是没有安装 SwissArmyTransformer ``pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-deps "SwissArmyTransformer> =0.3.6" 安装即可！
> > 好的多谢

您好，我按照您的命令安装好了sat，但是运行的时候 依然出现最   
 from sat.data_utils import make_loaders
ModuleNotFoundError: No module named 'sat'

我看了一下，好像是sat下没有data_utils.py, 请问您遇到过这类问题吗

**Comment by liudenghuiv** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
