### ISSUE TITLE
如何让模型下载到指定目录

### ISSUE THREAD

**Issue by PurpleMStone** [THUDM/VisualGLM-6B#64]
默认下到系统盘，但是系统盘没有空间了...想问下怎么改下载存放目录
<img width="1096" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/38729408/4a476fb6-e0a1-4a29-8766-8c3c6da1dad0">

**Comment by PurpleMStone** [comment]
export SAT_HOME=指定目录 就可以了
<img width="1341" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/38729408/a127bd4f-c306-4af7-b954-673afc86439f">

**Comment by Dittonal** [comment]
这个需要修改visualgml.py这个文件，在MODEL_URLS['visualglm-6b'] = 'https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1'这一行上一行加上os.environ.setdefault('SAT_HOME', "root/data/")
