### ISSUE TITLE
模型微调出错

### ISSUE THREAD

**Issue by 2132660698** [THUDM/VisualGLM-6B#78]
![image](https://github.com/THUDM/VisualGLM-6B/assets/94035926/9d78a477-6b77-4c91-9999-ed6179d8b8b2)

AttributeError 'FakeTokenizer' object has no attribute 'pad_token_id'
AttributeError 'FakeTokenizer' object has no attribute 'encode'
这两个都出现过。

**Comment by 1049451037** [comment]
看起来是tokenizer加载错误，是不是在调用get_tokenizer函数的时候args.tokenizer_type不对，正常来说如果args是VisualGLMModel.from_pretrained返回的结果的话，应该会被覆盖为`THUDM/chatglm-6b`。

```
model, args = FineTuneVisualGLMModel.from_pretrained('visualglm-6b', args)
# args.tokenizer_type == 'THUDM/chatglm-6b'
tokenizer = get_tokenizer(args)
```

**Comment by 2132660698** [comment]
model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)
args 的值打印如下：
![image](https://github.com/THUDM/VisualGLM-6B/assets/94035926/aa562a00-d19c-4e61-8fdd-a1ea5b1981d1)

**Comment by 1049451037** [comment]
呃……可以直接print一下args.tokenizer_type吗，这一屏幕字符串也很难找

**Comment by 1049451037** [comment]
如果args.tokenizer_type不等于'THUDM/chatglm-6b'就说明模型加载有问题，可以检查一下模型checkpoint里的`model_config.json`

**Comment by 2132660698** [comment]
呃……可以直接print一下args.tokenizer_type吗，这一屏幕字符串也很难找
是这个：
![image](https://github.com/THUDM/VisualGLM-6B/assets/94035926/249a88e5-0837-4d91-bead-a88230cd62f0)

**Comment by 2132660698** [comment]
![image](https://github.com/THUDM/VisualGLM-6B/assets/94035926/01650bb9-7ba2-4900-8240-6b3257f7339a)
我用的这个训练的

**Comment by 1049451037** [comment]
那应该可以正常加载tokenizer呀，可以print一下get_tokenizer返回的tokenizer是什么吗

**Comment by 2132660698** [comment]
报错前打印这个，是不是网络下载的问题呢？
![image](https://github.com/THUDM/VisualGLM-6B/assets/94035926/15d24970-1dcf-4a56-aaca-c8354d7de839)

**Comment by 1049451037** [comment]
是的，应该是网络的问题

**Comment by 2132660698** [comment]
这个可以配置本地加载吗？

**Comment by 1049451037** [comment]
把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了

**Comment by 2132660698** [comment]
> 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了

这个配置成本地后，问题解决了，非常感谢大家。

**Comment by Tate2099** [comment]
> 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了

请问下这一步具体如何操作？

**Comment by 20191864218** [comment]
> > 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了
> 
> 请问下这一步具体如何操作？

找到你下载的14个G的那个visualglm-6b.zip，然后unzip，然后解压的文件里面有个model_config.json文件，里面的tokenizer_type改成你本地的模型地址，具体修改json文件的方法去搜一下就可以

**Comment by chenchen333-dev** [comment]
> > 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了
> 
> 这个配置成本地后，问题解决了，非常感谢大家。

我改成本地的模型路径后依然报这个错，请问怎么解决呢

**Comment by chenchen333-dev** [comment]
> 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了

tokenizer的相关代码是指哪些？

**Comment by chenchen333-dev** [comment]
> > 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了
> 
> 这个配置成本地后，问题解决了，非常感谢大家。

是配置本地的visualglm-6b路径还是chatglm-6b路径呢？

**Comment by chenchen333-dev** [comment]
> 把tokenizer的[相关代码](https://huggingface.co/THUDM/chatglm-6b)复制到本地，然后把`args.tokenizer_type='THUDM/chatglm-6b'`替换成本地的路径就可以了

args.tokenizer_type='THUDM/chatglm-6b'是在哪个文件呢？
