### ISSUE TITLE
输入一张数学试卷，输出了一堆随机数

### ISSUE THREAD

**Issue by changjiuxiong** [THUDM/VisualGLM-6B#8]
输入的图片：https://picdl.sunbangyan.cn/2023/05/18/sue5dn.jpg
输入的文字：描述这张图片。
输出：20,36,48,57,69,76,87,95,104,113,122,131,140,149,158,167,176,185,194,203,212,221,230,239,248,257,266,275,284,293,302,311,320,329,338,347,356,365,374,383,392,401,410,419,428,437,446,455,464,473,482,491,500,509,518,527,536,545,554,563,572,581,590,599,608,617,626,635,644,653,662,671,680,689,698,707,716,725,734,743,752,761,770,779,788,797,806,815,824,833,842,851,860,869,878.

**Comment by Sleepychord** [comment]
可能是在计算空吧，但是显然没有学会这个问题QAQ这个版本确实没办法处理太复杂的情况，我们继续更新，感谢您的反馈。
