### ISSUE TITLE
QLoRA微调问题

### ISSUE THREAD

**Issue by lljjson** [THUDM/VisualGLM-6B#85]
代码小白，其他步骤均跑通，受限于只有12g显存，尝试了刚更新的bash finetune/finetune_visualglm_qlora.sh
 File "/GLM/VisualGLM-6B-main/lora_mixin.py", line 62, in __init__
    self.original = HackLinearNF4(in_dim, out_dim)
NameError: name 'HackLinearNF4' is not defined. Did you mean: 'HackLinear'?
卡在了奇怪的位置

**Comment by dizhenx** [comment]
> 

应该跟显存没有关系，我也报这个错，应该是代码写的有问题，期待官方修改一下

**Comment by 1049451037** [comment]
应该是你没有安装`bitsandbytes`，需要`pip install bitsandbytes`

**Comment by dizhenx** [comment]
> 应该是你没有安装`bitsandbytes`，需要`pip install bitsandbytes`

不是，安了还报错

**Comment by 1049451037** [comment]
具体报什么错呢？有更多的报错信息吗

**Comment by 1049451037** [comment]
运行`from bitsandbytes.nn import LinearNF4`这句python试一下报什么错

**Comment by dizhenx** [comment]
> 具体报什么错呢？有更多的报错信息吗
安了之后报错跟没安的时候一样,还是这个错。
bash finetune/finetune_visualglm_qlora.sh
File "/GLM/VisualGLM-6B-main/lora_mixin.py", line 62, in init
self.original = HackLinearNF4(in_dim, out_dim)
NameError: name 'HackLinearNF4' is not defined. Did you mean: 'HackLinear'?
如果没安bitsandbytes，应该不会直接报以上错误，应该会报no moduel named bitsandbytes。所以感觉跟这个没关系

**Comment by 1049451037** [comment]
用python运行`from bitsandbytes.nn import LinearNF4`这句试一下报什么错

**Comment by dizhenx** [comment]
> 用python运行`from bitsandbytes.nn import LinearNF4`这句试一下报什么错

ModuleNotFoundError: No module named 'scipy'

**Comment by 1049451037** [comment]
那就再`pip install scipy`一下应该就好了
