### ISSUE TITLE
本地加载模型室提示找不到 model_config.json

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [THUDM/VisualGLM-6B#9]
如题，使用的虚拟环境，已经安装所需依赖。在 HuggingFace 上下载的模型，放置到本地文件夹 /data/models/THUDM/visualglm-6b 中。修改 cli_demo.py：
```
def main():
    ...
    # load model
    model, model_args = VisualGLMModel.from_pretrained(
        "/data/models/THUDM/visualglm-6b",
        args=argparse.Namespace(
        fp16=True,
        skip_init=True,
        use_gpu_initialization=True if (torch.cuda.is_available() and args.quant is None) else False,
        device='cuda' if (torch.cuda.is_available() and args.quant is None) else 'cpu',
        local_files_only=1,
    ))
    ...
    tokenizer = AutoTokenizer.from_pretrained("/data/models/THUDM/visualglm-6b", local_files_only=1, trust_remote_code=True)
    ...
```
![2023-05-18_18-47-23_VisualGLM-6B – cli_demo py](https://github.com/THUDM/VisualGLM-6B/assets/63704404/a41679c4-04d2-4e39-ae57-7000971c440e)

运行 cli_demo.py 时报错如下：
```
Traceback (most recent call last):
  File "/data/VisualGLM-6B/cli_demo.py", line 100, in <module>
    main()
  File "/data/VisualGLM-6B/cli_demo.py", line 25, in main
    model, model_args = VisualGLMModel.from_pretrained(
  File "/data/VisualGLM-6B/.venv/lib/python3.9/site-packages/sat/model/base_model.py", line 212, in from_pretrained
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/data/VisualGLM-6B/.venv/lib/python3.9/site-packages/sat/arguments.py", line 423, in update_args_with_file
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/models/THUDM/visualglm-6b/model_config.json'
```
![2023-05-18_18-47-52_Administrator Windows PowerShell](https://github.com/THUDM/VisualGLM-6B/assets/63704404/8a5b53ae-e6db-45d1-a393-7265033e257d)

放置模型的目录结构如下：
![2023-05-18_18-45-43_visualglm-6b](https://github.com/THUDM/VisualGLM-6B/assets/63704404/6d3216c3-4bf3-4cb1-98dc-4ce34cfd9280)

**Comment by Sleepychord** [comment]
Huggingface的模型请运行cli_demo_hf.py，而不是cli_demo.py，后者支持的是sat格式的模型。
如果要使用`cli_demo.py`，您可以直接运行它，会自动从清华云盘下载模型（一个zip包，支持断点续传）并解压缩（你也可以在visualglm.py中找到zip包的地址手动下载）。

**Comment by yyxx1997** [comment]
这种低级问题都不修改或者说明一下吗，你们上传这个模型之前都不自己跑跑吗？？？

**Comment by Sleepychord** [comment]
@yyxx1997 这是提问者运行错文件了而已，我们readme里没写错，不需要修改。

**Comment by frnksmdlkedjnfr** [comment]
各位莫喷，用带 _hf 后缀的就可以运行了

**Comment by Senna1960321** [comment]
> @yyxx1997 这是提问者运行错文件了而已，我们readme里没写错，不需要修改。

您好，为什么我运行_hf文件也显示No module named 'sat'

**Comment by yumulinfeng1** [comment]
> pip install SwissArmyTransformer

你好  这个SwissArmyTransformer要求>0.3.6,可是运行
pip install SwissArmyTransformer显示ERROR: Could not find a version that satisfies the requirement SwissArmyTransformer==0.3.6 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.11, 0.2.12, 0.3.1, 0.3.2)

最高版本只到0.3.2。  安装完0.3.2后运行python web_demo_hf.py报错如下




│ /ddd/xxx/anaconda/envs/py37df/lib/python3.7/site-packages/sat/model/base_model.py:241 in │
│ get_args                                                                                         │
│                                                                                                  │
│   238 │   │   │   if hasattr(args, k):                                                           │
│   239 │   │   │   │   setattr(args, k, v)                                                        │
│   240 │   │   │   else:                                                                          │
│ ❱ 241 │   │   │   │   raise ValueError(f'Unknown arg {k}.')                                      │
│   242 │   │   return args                                                                        │
│   243                                                                                            │
│   244 class AutoModel():                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Unknown arg use_final_layernorm.

**Comment by Captain1986** [comment]
> Huggingface的模型请运行cli_demo_hf.py，而不是cli_demo.py，后者支持的是sat格式的模型。 如果要使用`cli_demo.py`，您可以直接运行它，会自动从清华云盘下载模型（一个zip包，支持断点续传）并解压缩（你也可以在visualglm.py中找到zip包的地址手动下载）。
“会自动从清华云盘下载模型（一个zip包，支持断点续传）并解压缩”，是会下载一个visualglm-6b.zip文件，但是很小，而且报错“BadZipFile: File is not a zip file”

**Comment by ttyuuuuuuuuuu** [comment]
> > Huggingface的模型请运行cli_demo_hf.py，而不是cli_demo.py，后者支持的是sat格式的模型。 如果要使用`cli_demo.py`，您可以直接运行它，会自动从清华云盘下载模型（一个zip包，支持断点续传）并解压缩（你也可以在visualglm.py中找到zip包的地址手动下载）。
> > “会自动从清华云盘下载模型（一个zip包，支持断点续传）并解压缩”，是会下载一个visualglm-6b.zip文件，但是很小，而且报错“BadZipFile: File is not a zip file”

但是在这里没找到visualglm-6b的地址：
![image](https://github.com/THUDM/VisualGLM-6B/assets/51437324/6c4f273f-7f2b-49b8-ae7a-aa76898dc331)
![image](https://github.com/THUDM/VisualGLM-6B/assets/51437324/81b42278-aaa4-4713-9349-6675c6254d33)
![image](https://github.com/THUDM/VisualGLM-6B/assets/51437324/1b8b4391-5f3c-4a1f-8d11-c94994dba330)
![image](https://github.com/THUDM/VisualGLM-6B/assets/51437324/f87b3efb-ab65-4e6a-adac-c4c21981ba75)

**Comment by Roronoayx** [comment]
> 各位莫喷，用带 _hf 后缀的就可以运行了

那请问如果要微调的话，它好像默认调用sat格式的，怎么办呢，微调能使用hf的模型吗？

**Comment by horrybe** [comment]
script_path=$(realpath $0)
script_dir=$(dirname $script_path)
main_dir=$(dirname $script_dir)
请问你们这个路径是什么个意思，什么script路径？什么script的文件夹？都不给个注释的？

**Comment by qqq286** [comment]
> > 各位莫喷，用带 _hf 后缀的就可以运行了
> 
> 那请问如果要微调的话，它好像默认调用sat格式的，怎么办呢，微调能使用hf的模型吗？

同问

**Comment by liasazhang** [comment]
> > > 各位莫喷，用带 _hf 后缀的就可以运行了
> > 
> > 
> > 那请问如果要微调的话，它好像默认调用sat格式的，怎么办呢，微调能使用hf的模型吗？
> 
> 同问

加一,微调要怎么搞呀
