### ISSUE TITLE
为什么使用swissarmytransformer里面需要加载chatglm-6b的tokenizer

### ISSUE THREAD

**Issue by ywm12345** [THUDM/VisualGLM-6B#99]
![图片](https://github.com/THUDM/VisualGLM-6B/assets/85282624/4902f64b-cf49-4c15-bc7f-8e6003cbf250)
使用visualglm-6b的是不也可以

**Comment by Sleepychord** [comment]
sat目前主要还是管理模型，而tokenizer的管理相当繁琐，我们直接用了transformers来管理。
